apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-02-17T18:12:52Z"
  generation: 1
  labels:
    app: fedora-undertow-jdk17
  name: fedora-undertow-jdk17
  namespace: default
  resourceVersion: "126262"
  uid: aa35e976-ade4-4f7b-880f-0d657099da4f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fedora-undertow-jdk17
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fedora-undertow-jdk17
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=0.8 -Xlog:os+container=trace -Xlog:gc=info
        image: quay.io/sgehwolf/fedora-35-undertow:jdk17
        imagePullPolicy: IfNotPresent
        name: fedora-35-undertow
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-17T18:12:58Z"
    lastUpdateTime: "2022-02-17T18:12:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-17T18:12:53Z"
    lastUpdateTime: "2022-02-17T18:12:58Z"
    message: ReplicaSet "fedora-undertow-jdk17-c667567cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
